name: Jvar.nl
description: Professional PHP and NodeJS developer
meta_description: "Done projects and stuff."

aboutPage: true

highlighter: rouge

paginate: 5
baseurl: /
domain_name: "http://jvar.nl"
google_analytics: "UA-32550863-6"

# Details for the RSS feed generator
url: "http://jvar.nl"
author: "Jasper van Rijbroek"
authorTwitter: "JaspervanRijbro"

permalink: /:year/:title/

plugins: [jekyll-paginate, jekyll-feed, jekyll-sitemap]

collections:
    category:
        output: true

defaults:
    - scope:
          path: "" # empty string for all files
          type: pages
      values:
          layout: default
    - scope:
          path: "" # empty string for all files
          type: posts
      values:
          layout: post
    - scope:
          path: ""
          type: category
      values:
          layout: "category"
