version: "3"
services:
  node:
    env_file:
      - "./.dev/.env"
    image: "library/node:14"
    working_dir: "/app"
    user: "1000:1000"
    volumes:
      - ".:/app"
    ports:
      - "8000:8000"
  php:
    image: "php:7.4-cli"
    working_dir: "/app"
    user: "1000:1000"
    volumes:
      - "./test:/app"
    ports:
      - "8000:8000"
