name: Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Publish Gatsby Site
      uses: xmflsct/action-publish-gatsby@v1.0.0
      env:
        ALGOLIA_APP_ID: ${{ secrets.algolia_app_id }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.algolia_admin_key }}
        GOOGLE_ANALYTICS_KEY: "UA-32550863-6"
      with:
        publishBranch: "master"
        token: ${{ secrets.push_token }}
        name: "Jasper van Rijbroek"
        email: "jasper@jvar.nl"
