name: Deploy

on:
  push:
    branches: [ code ]
  pull_request:
    branches: [ code ]
  repository_dispatch:
    types: [ publish-event ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache yarn directory
      id: yarn-cache-dir
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Yarn cache
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: Yarn install
      run: 'yarn install --pure-lockfile'

    - name: Gatsby Cache Folder
      uses: actions/cache@v2
      with:
        key: gatsby-cache-folder
        path: .cache

    - name: Gatsby Public Folder
      uses: actions/cache@v2
      with:
        key: gatsby-public-folder
        path: public

    - name: Build gatsby
      run: 'yarn run build:incremental'
      env:
        ALGOLIA_APP_ID: ${{ secrets.algolia_app_id }}
        ALGOLIA_ADMIN_KEY: ${{ secrets.algolia_admin_key }}
        CONTENTFUL_SPACE_ID: ${{ secrets.contentful_space_id }}
        CONTENTFUL_ACCESS_TOKEN: ${{ secrets.contentful_access_token }}
        GOOGLE_ANALYTICS_KEY: "UA-32550863-6"

    - name: Deploy gatsby
      run: yarn run gh-pages -d public -b master -u "Jasper van Rijbroek" ''<'"jasper@jvar.nl"'>' -r 'https://${{ secrets.push_token }}@github.com/'"$GITHUB_REPOSITORY"'.git' -m 'Build of '"$GITHUB_SHA"''
